### ISSUE TITLE
Comments are removed when path is replaced

### ISSUE THREAD

**Issue by dogoku** [codemod-js/codemod#191]
This might be related to #168 

I have a very simple example transform [here](https://astexplorer.net/#/gist/fa9f3295d4910aa7358a9497438a08d1/03c9cb12998e5a1247b4dabc3aa71918064a2a2e)

The ast-explorer example above is set to babylon6 and babel6, which has exactly the same behavior as running this transform via `@codemod/cli`

If I set it to babylon7 and babel7, it doesn't remove the comment.

It's a bug regardless, but I'm curious why it's happening, given that `@codemod/cli` uses `@babel/core@7.2.0`

**Comment by eventualbuddha** [comment]
This is due to the difference in the way recast and babel handle comments. [You can use `@resugar/helper-comments` to do the path replacement](https://github.com/resugar/resugar/blob/d5689e3a74dd05edb6449e90ff4a7eb1f5629a18/packages/resugar-helper-comments/src/index.ts#L13-L47) which will handle preserving comments for you. I should probably incorporate that functionality into `@codemod/core` somehow.
