### ISSUE TITLE
Bug? (babelrc options not work) + Use case (need to pass fn to plugin options) 

### ISSUE THREAD

**Issue by arestov** [codemod-js/codemod#699]
Use case: I need to pass function to plugin options (`replacer` for `babel-plugin-replace-imports`).

There is no way to do it using `--plugin-options` (only json supported)

So I have to use `.babelrc.js`

setup:
`node -v: v12.18.0`
`"@codemod/cli": "^2.2.1"`
my `.babelrc.js` content:
```
console.log(111111)

module.exports = {
  // "extends": "@babel/preset-env",
  "plugins": [
    [
      "babel-plugin-replace-imports",
      {
        "test": /\/?regexp\//i,
        "replacer": () => {console.log(2222)}
      }
    ]
  ]
}
```

## 1. Just babelrc
`npm run codemod -- --find-babel-config  -p babel-plugin-replace-imports  js/libs/navi.js` 
result:
```
111111
Encountered an error while processing js/libs/navi.js:
Error: /Users/arestov/dkt/js/libs/navi.js: 
babel-plugin-replace-imports: options are required.
```
**`options are required.`**
expected result: 🙅‍♂️ no error 
(looks like options was not passed to plugin by cli)
## 2. babelrc + `--plugin-options`
`npm run codemod -- --find-babel-config  --plugin-options babel-plugin-replace-imports='{"ff": 55}' -p babel-plugin-replace-imports  js/libs/navi.js`
result:
```
111111
Encountered an error while processing js/libs/navi.js:
Error: /Users/arestov/dkt/js/libs/navi.js: 
babel-plugin-replace-imports: «test» option is required.
```
**`«test» option is required.`**
expected result: ❓ 
(shouldn't cli prefer babelrc?)
(`--plugin-options` was used, looks like options was not passed to plugin by cli)

## 3. alt babelrc (short/compact plugins) + `--plugin-options`
`.babelrc.js`
```
console.log(111111)

module.exports = {
  // "extends": "@babel/preset-env",
  "plugins": [
    [
      "babel-plugin-replace-imports",
    ]
  ]
}
```
`npm run codemod -- --find-babel-config  --plugin-options babel-plugin-replace-imports='{"ff": 55}' -p babel-plugin-replace-imports  js/libs/navi.js`
```
111111
Encountered an error while processing js/libs/navi.js:
Error: /Users/arestov/dkt/js/libs/navi.js: 
babel-plugin-replace-imports: options are required.
```
**`options are required.`**
expected result: 🙅‍♂️ no error
(`--plugin-options` was not used, looks like empty options in plugins list was selected by cli)

## 4. @codemod/core
tt.js
```
var { transform } = require('@codemod/core')


const result = transform('import k from "nothing";import j from "something";', {
  'plugins': [
    [
      'babel-plugin-replace-imports',
      {
        'test': /nothing/i,
        'replacer': () => {
          console.log('replacing!')
          return 11
        }
      }
    ]
  ]
})

console.log(result.code)

```
`node tt.js`
result:
```
replacing!
import k from "11";import j from "something";
```

**Comment by eventualbuddha** [comment]
Thanks for the issue. I was confused by this for a bit because I never use the `--find-babel-config` option myself. The problem is that when you use `--find-babel-config` you're telling Babel to use the `.babelrc.js` file and to load all the plugins mentioned in it. Then you're _also_ telling codemod to load the `babel-plugin-replace-import` plugin, but without providing options properly. The end result is that Babel tries to process your code with the plugin **twice**, once with the right options and once without. That's the the last example you provided, using `@codemod/core` directly, worked as expected -- you weren't telling Babel to load the plugin.

This could certainly be improved from a documentation perspective, and maybe something in tooling as well. One way might be to allow loading plugin options from JavaScript files, like this:

```
codemod -p babel-plugin-replace-imports -o @bpri-opts.js js/libs/navi.js
```

Would that be useful? Or would you just prefer to keep it in `.babelrc.js` and run like this?

```
codemod --find-babel-config js/libs/navi.js
```

**Comment by arestov** [comment]
thank you for clarification! 🙏 
`-o @bpri-opts.js` would be perfect for my case

p.s. currently i've complete my task already (using `var { transform } = require('@codemod/core')`, glue and `gulp`) 
and **looks like it could be done using `cli` with target plugins inside config and dummy plugin (if `-p ` is required)**, is it correct?
