### ISSUE TITLE
Run with a custom babel.config.js

### ISSUE THREAD

**Issue by MarceloPrado** [codemod-js/codemod#917]
Hi! 
First and foremost, thanks for working on this package. 

I'm building a codemod to parse metrics against several git repositories. Each repo has a different babel config. While the default options provided by `@codemod/parser` works for the majority of use cases, some repos throw a parsing error. 

One example is: `Abstract methods can only appear within an abstract class.`. I tried upgrading my @babel/core to the latest but had no success (see GH [issue](https://github.com/babel/babel/issues/12745)).

While I can try wrestling with babel a bit more, I'm pretty sure I'll face other errors once I start working with more repos. I was wondering if there's a way I can tell `@codemod/cli` to use a custom babel config. For instance:
```
yarn codemod --plugin myCodemod.ts --babelConfig repo-a/babel.config.js repo-a/
```

**Comment by eventualbuddha** [comment]
`@codemod/core` used to be able to load files using a `babel.config.js`, but I took that feature out because it seemed to add a lot of complexity for minimal benefit. The particular bug you mentioned seems to be a bad interaction between the `placeholders` and `typescript` parser plugins, so I fixed that by disabling the `placeholders` plugin by default. Let me know if you have any other issues!
